model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/my_azure_deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: 'os.environ/AZURE_API_KEY'
      api_version: '2025-01-01-preview' # [OPTIONAL] litellm uses the latest azure api_version by default

general_settings:
  master_key: sk-1234
  database_url: 'postgresql://<user>:<password>@<host>:<port>/<dbname>' # ðŸ‘ˆ KEY CHANGE
